"""Public re-export surface for canonical domain types."""

from packages.domain.entities import (
    AddressFamily,
    CanonicalEntity,
    CanonicalEntityPayload,
    ComponentEntity,
    ComponentProperties,
    ConnectionEntity,
    ConnectionProperties,
    ContainerEntity,
    ContainerProperties,
    DeviceEntity,
    DeviceProperties,
    Entity,
    EntityProperties,
    EvidenceBackedEntity,
    FirewallEntity,
    FirewallProperties,
    InterfaceEntity,
    InterfaceProperties,
    IPAddressEntity,
    IPAddressProperties,
    LifecycleState,
    LinkStatus,
    NetworkEntity,
    NetworkProperties,
    RouteEntity,
    RouteProperties,
    ServiceEntity,
    ServiceProperties,
    SiteEntity,
    SiteProperties,
    VlanEntity,
    VlanProperties,
)
from packages.domain.enums import ConfidenceLevel, EntityType, ExtractionMethod, RelationshipType
from packages.domain.evidence import Confidence, Evidence, SourceLocation
from packages.domain.identity import (
    ComponentIdentity,
    ConnectionIdentity,
    ContainerIdentity,
    DeviceIdentity,
    EntityIdentity,
    FirewallIdentity,
    InterfaceIdentity,
    IPIdentity,
    NetworkIdentity,
    RouteIdentity,
    ServiceIdentity,
    SiteIdentity,
    VlanIdentity,
)
from packages.domain.ids import PLATFORM_NAMESPACE, generate_entity_id, generate_relationship_id
from packages.domain.relationships import EvidenceBackedRelationship, Relationship
from packages.domain.scope import CanonicalIdentity, GraphScope

__all__ = [
    "AddressFamily",
    "CanonicalEntity",
    "CanonicalEntityPayload",
    "CanonicalIdentity",
    "ComponentEntity",
    "ComponentIdentity",
    "ComponentProperties",
    "Confidence",
    "ConfidenceLevel",
    "ConnectionEntity",
    "ConnectionIdentity",
    "ConnectionProperties",
    "ContainerEntity",
    "ContainerIdentity",
    "ContainerProperties",
    "DeviceEntity",
    "DeviceIdentity",
    "DeviceProperties",
    "Entity",
    "EntityIdentity",
    "EntityProperties",
    "EntityType",
    "Evidence",
    "EvidenceBackedEntity",
    "EvidenceBackedRelationship",
    "ExtractionMethod",
    "FirewallEntity",
    "FirewallIdentity",
    "FirewallProperties",
    "GraphScope",
    "IPAddressEntity",
    "IPAddressProperties",
    "IPIdentity",
    "InterfaceEntity",
    "InterfaceIdentity",
    "InterfaceProperties",
    "LifecycleState",
    "LinkStatus",
    "NetworkEntity",
    "NetworkIdentity",
    "NetworkProperties",
    "PLATFORM_NAMESPACE",
    "Relationship",
    "RelationshipType",
    "RouteEntity",
    "RouteIdentity",
    "RouteProperties",
    "ServiceEntity",
    "ServiceIdentity",
    "ServiceProperties",
    "SiteEntity",
    "SiteIdentity",
    "SiteProperties",
    "SourceLocation",
    "VlanEntity",
    "VlanIdentity",
    "VlanProperties",
    "generate_entity_id",
    "generate_relationship_id",
]
